[workspace]
authors = ["JeanBilheux <bilheuxjm@ornl.gov>"]
channels = ["conda-forge"]
name = "python_101"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
scitiff = ">=25.7.0,<26"
python = ">=3.13.9,<3.14"
jupyterlab = ">=4.4.10,<5"
matplotlib = ">=3.10.7,<4"
