[workspace]
authors = ["JeanBilheux <bilheuxjm@ornl.gov>"]
channels = ["conda-forge"]
name = "scipp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
scitiff = ">=25.7.0,<26"
numpy = ">=2.3.4,<3"
matplotlib = ">=3.10.7,<4"
ipywidgets = ">=8.1.8,<9"
ipykernel = ">=7.1.0,<8"
